"""Add link_token field to Form model

Revision ID: e7ecad79269d
Revises: 
Create Date: 2024-10-30 08:43:18.566371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7ecad79269d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_token', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint('uq_forms_link_token', ['link_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_constraint('uq_forms_link_token', type_='unique')
        batch_op.drop_column('link_token')
    # ### end Alembic commands ###
